{% set name = "drf-spectacular-sidecar" %}
{% set version = "2025.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/drf_spectacular_sidecar-{{ version }}.tar.gz
  sha256: d25d82ea2e6176ce4583812f73ac9f177dcd56141c11a9e9bf35f1b1878d5044

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }},<4.0
    - django >=2.2

test:
  imports:
    - drf_spectacular_sidecar
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tfranzel/drf-spectacular-sidecar
  summary: Serve self-contained distribution builds of Swagger UI and Redoc with Django
  dev_url: https://github.com/tfranzel/drf-spectacular-sidecar
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - cshaley
