{% set name = "drf-spectacular-sidecar" %}
{% set version = "2023.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/drf-spectacular-sidecar-{{ version }}.tar.gz
  sha256: 546a83c173589715e530fad211af60cbcda2db54eb9e0935d44251639332af6d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - pip
  run:
    - python >=3.7,<4.0
    - django >=2.2

test:
  imports:
    - drf_spectacular_sidecar
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tfranzel/drf-spectacular-sidecar
  summary: Serve self-contained distribution builds of Swagger UI and Redoc with Django
  dev_url: https://github.com/tfranzel/drf-spectacular-sidecar
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - cshaley
